[tool.poetry]
name = "helpers"
version = "0.1.0"
description = ""
authors = ["Arcanum AI"]
readme = "README.md"
packages = [
    { include = "helpers" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

structlog = "25.1.0"

[tool.poetry.group.dev.dependencies]
mypy = "1.14.1"
pylint = "3.3.4"
pyright = "1.1.393"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
