[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "policy-builder-expert-review"
version = "0.1.0"
description = "Part of the policy builder Step Function"
authors = ["Arcanum AI"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

aws-lambda-powertools = "3.9.0"
bedrock = {path = "../../../lib/bedrock", develop = true}
prm = {path = "../../../lib/prm", develop = true}
helpers = {path = "../../../lib/helpers", develop = true}
structlog = "25.2.0"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "1.40.25"
mypy = "1.17.1"
pylint = "3.3.8"
pyright = "1.1.403"
[tool.poetry.group.boto.dependencies]
boto3 = "1.40.25"
