"""Pipeline orchestrator for Nolia Funding application assessment.

Three-phase pipeline:
    Phase 1: Extract applicant info  — nolia-funding-assess-extract
    Phase 2: Evaluate against rules  — nolia-funding-assess-evaluate
    Phase 3: Render output template  — nolia-funding-assess-render

Pre-pipeline:
    - ``setup_funding_assess_workspace()`` downloads the paired Global KB
      rules + Funding KB contents (rules, supporting data, templates) and
      pre-extracts supporting-data PDFs.
    - ``extract_funding_application()`` extracts every applicant-uploaded
      file (PDF, DOCX, etc.) into per-file extracted JSONs.

Post-pipeline:
    - ``output_conversion`` converts the rendered MD to PDF + DOCX.
    - Final S3 sync + ``_result.json`` write.
"""

import os
import shutil
import time
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

import structlog

from ..base import AgentTypeConfig
from ..registry import get_agent_type_config
from .output_conversion import convert_md_to_pdf_and_docx
from .workspace_setup import (
    OUTPUTS_DIR,
    TMP_DIR,
    extract_funding_application,
    setup_funding_assess_workspace,
)

logger = structlog.get_logger()

AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")


def _emit_progress(
    user_sub: str,
    conversation_id: str,
    s3_prefix: str | None,
    events: list[dict],
    phase: str,
    message: str,
) -> None:
    """Append a progress event and write _progress.json to S3."""
    from ...s3_workspace import write_progress_to_s3

    events.append(
        {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "phase": phase,
            "message": message,
        }
    )
    write_progress_to_s3(user_sub, conversation_id, events, s3_prefix=s3_prefix)


async def run_nolia_funding_assess_pipeline(
    prompt: str,
    user_sub: str,
    conversation_id: str,
    parent_config: AgentTypeConfig,
    *,
    timezone: Optional[str] = None,
    user_email: Optional[str] = None,
    today_string: Optional[str] = None,
    available_kbs: Optional[list[dict]] = None,
    enabled_tools: Optional[list[str]] = None,
    model_id: Optional[str] = None,
    request_id: Optional[str] = None,
    attached_files: Optional[list[dict]] = None,
    attached_folders: Optional[list[dict]] = None,
    kb_listings: Optional[dict[str, dict]] = None,
    external_user_id: Optional[str] = None,
    enabled_integrations: Optional[list[str]] = None,
    request_metadata: Optional[dict] = None,
    **_kwargs: Any,
) -> dict[str, Any]:
    """Run the Nolia Funding assessment pipeline end-to-end.

    Args:
        prompt: User prompt (typically auto-generated by the trigger).
        user_sub: Cognito user sub.
        conversation_id: Run ID for this assessment.
        parent_config: The nolia-funding-assess AgentTypeConfig.
        request_metadata:
            Required:
              - ``global_kb_id`` — UUID of the paired Global KB
              - ``funding_kb_id`` — UUID of the specific Fund/Grant/Scholarship KB
              - ``client_name`` — for logging + future client dispatch
            Optional:
              - ``applicant_id`` — cosmetic run handle (e.g. ``"APP-A1B2C3"``).
                Phase 1 always extracts the *real* applicant name from the
                documents; ``applicant_id`` is purely for pre-extraction UI
                display and shareable URLs. Frontend may leave this empty —
                the assessment's canonical identity still comes from the
                extracted ``applicant.json``.
        **_kwargs: Standard pipeline kwargs forwarded to run_claude_sdk.

    Returns:
        dict with status, text, artifacts, usage, steps, applicant info,
        and a needs_review flag.
    """
    pipeline_start = time.monotonic()
    metadata = request_metadata or {}
    global_kb_id = metadata.get("global_kb_id", "")
    funding_kb_id = metadata.get("funding_kb_id", "")
    applicant_id = metadata.get("applicant_id", "")
    client_name = metadata.get("client_name", "")

    logger.info(
        "Starting Nolia Funding assess pipeline",
        _name="NOLIA_FUNDING_ASSESS_PIPELINE_START",
        phase="pipeline",
        global_kb_id=global_kb_id,
        funding_kb_id=funding_kb_id,
        applicant_id=applicant_id,
        client_name=client_name,
        conversation_id=conversation_id,
    )

    s3_prefix_fmt = parent_config.s3_prefix_template.format(
        user_sub=user_sub,
        conversation_id=conversation_id,
    )
    progress_events: list[dict] = []

    def emit(phase: str, message: str) -> None:
        _emit_progress(
            user_sub, conversation_id, s3_prefix_fmt, progress_events, phase, message
        )

    # ── Pre-pipeline: KB download + applicant doc extraction ───────────────
    emit("download", "Loading selection criteria and supporting data...")
    await setup_funding_assess_workspace(
        user_sub,
        conversation_id,
        global_kb_id=global_kb_id,
        funding_kb_id=funding_kb_id,
    )

    emit("extract-uploads", "Reading applicant documents...")
    extracted = await extract_funding_application(s3_prefix_fmt)
    logger.info(
        "Applicant extraction complete",
        _name="NOLIA_FUNDING_ASSESS_EXTRACTION_DONE",
        phase="pipeline",
        extracted_count=len(extracted),
    )

    # ── Step-specific user prompts ──────────────────────────────────────────
    user_context = (
        f"Assess this funding application. Applicant ID: {applicant_id or 'Not available'}. "
        f"Funding KB: {funding_kb_id or 'unknown'}. "
        f"All inputs are in the workspace already."
    )

    extract_prompt = (
        f"{user_context}\n\n"
        "You are running Phase 1 (Extract Applicant Info). Read every "
        "extracted JSON in `/workdir/uploads/` and produce the unified "
        "applicant record at `/workdir/tmp/applicant.json`."
    )

    evaluate_prompt = (
        f"{user_context}\n\n"
        "You are running Phase 2 (Evaluate). Phase 1 produced the applicant "
        "record at `/workdir/tmp/applicant.json`. Read the rulebook at "
        "`/workdir/knowledge-bases/funding-rules.md` and evaluate each rule "
        "against the application, querying supporting data files as needed. "
        "Write your structured findings to `/workdir/tmp/findings.md`."
    )

    render_prompt = (
        f"{user_context}\n\n"
        "You are running Phase 3 (Render). Phases 1 and 2 are complete — "
        "applicant info at `/workdir/tmp/applicant.json`, findings at "
        "`/workdir/tmp/findings.md`. Read the output template in "
        "`/workdir/knowledge-bases/templates/`, fill it according to its "
        "bracketed instructions, and write the result to "
        "`/workdir/outputs/Assessment_<applicant_name>.md`. "
        "Then extend `/workdir/tmp/applicant.json` with a top-level "
        "`decision` block and (for scored Funds only) a top-level `score` "
        "field — see the Structured Decision & Score Output section of the "
        "system prompt for the exact shape. The frontend reads these "
        "directly."
    )

    step_kwargs = dict(
        prompt=prompt,
        user_sub=user_sub,
        conversation_id=conversation_id,
        timezone=timezone,
        user_email=user_email,
        today_string=today_string,
        available_kbs=available_kbs,
        enabled_tools=enabled_tools,
        request_id=request_id or str(uuid.uuid4()),
        attached_files=attached_files,
        attached_folders=attached_folders,
        kb_listings=kb_listings,
        external_user_id=external_user_id,
        enabled_integrations=enabled_integrations,
    )

    all_steps: list[dict[str, Any]] = []
    all_artifacts: list[dict] = []
    total_usage: dict[str, Any] = {
        "num_turns": 0,
        "total_cost_usd": 0.0,
        "duration_ms": 0,
    }

    def _accumulate(result: dict[str, Any], step_name: str) -> dict[str, Any]:
        usage = result.get("usage", {})
        all_steps.append(
            {
                "step": step_name,
                "step_number": len(all_steps) + 1,
                "status": result.get("status", "completed"),
                "text": result.get("text", ""),
                "usage": usage,
            }
        )
        all_artifacts.extend(result.get("artifacts", []))
        total_usage["num_turns"] += usage.get("num_turns", 0)
        total_usage["total_cost_usd"] += usage.get("total_cost_usd", 0.0)
        total_usage["duration_ms"] += usage.get("duration_ms", 0)
        return result

    def _check_error(result: dict[str, Any], step_name: str) -> bool:
        if result.get("status") == "error":
            logger.error(
                "Funding assess pipeline step failed",
                _name="NOLIA_FUNDING_ASSESS_STEP_ERROR",
                phase="pipeline",
                step=step_name,
                error=result.get("error", "unknown"),
            )
            return True
        return False

    # ── Phase 1: Extract applicant info ─────────────────────────────────────
    emit("extract", "Identifying applicant and requested funding...")
    extract_result = _accumulate(
        await _run_step(
            "nolia-funding-assess-extract",
            "extract",
            is_first_step=True,
            **{**step_kwargs, "prompt": extract_prompt},
        ),
        "nolia-funding-assess-extract",
    )
    if _check_error(extract_result, "nolia-funding-assess-extract"):
        return _build_error_result(
            all_steps,
            all_artifacts,
            total_usage,
            "Phase 1 (Extract applicant info) failed",
            applicant_id=applicant_id,
        )

    # Publish the applicant-preview to S3 as soon as Phase 1 succeeds, so
    # the frontend can poll for it and show the extracted applicant name
    # on the activity-table row while Phase 2 + Phase 3 are still running.
    # Total pipeline is 2–3 min; Phase 1 is ~30s. Without this, the row
    # shows a runId placeholder for the full duration.
    _write_applicant_preview_to_s3(
        user_sub=user_sub,
        conversation_id=conversation_id,
        s3_prefix=s3_prefix_fmt,
        applicant_id=applicant_id,
    )

    # ── Phase 2: Evaluate ──────────────────────────────────────────────────
    emit("evaluate", "Assessing application against selection criteria...")
    evaluate_result = _accumulate(
        await _run_step(
            "nolia-funding-assess-evaluate",
            "evaluate",
            **{**step_kwargs, "prompt": evaluate_prompt},
        ),
        "nolia-funding-assess-evaluate",
    )
    if _check_error(evaluate_result, "nolia-funding-assess-evaluate"):
        return _build_error_result(
            all_steps,
            all_artifacts,
            total_usage,
            "Phase 2 (Evaluate) failed",
            applicant_id=applicant_id,
        )

    # ── Phase 3: Render ────────────────────────────────────────────────────
    emit("render", "Drafting assessment report...")
    render_result = _accumulate(
        await _run_step(
            "nolia-funding-assess-render",
            "render",
            **{**step_kwargs, "prompt": render_prompt},
        ),
        "nolia-funding-assess-render",
    )
    if _check_error(render_result, "nolia-funding-assess-render"):
        return _build_error_result(
            all_steps,
            all_artifacts,
            total_usage,
            "Phase 3 (Render) failed",
            applicant_id=applicant_id,
        )

    # ── Post-pipeline: convert rendered MD to PDF + DOCX ───────────────────
    emit("convert", "Preparing downloadable versions (PDF and Word)...")
    rendered_md = _find_rendered_assessment()
    converted: dict[str, Any] = {"pdf": None, "docx": None}
    if rendered_md is not None:
        converted = await convert_md_to_pdf_and_docx(rendered_md, s3_prefix_fmt)
        for fmt, path in converted.items():
            if path is not None:
                all_artifacts.append({"type": "file", "path": f"outputs/{path.name}"})
        # Also include the MD itself
        all_artifacts.append({"type": "file", "path": f"outputs/{rendered_md.name}"})
    else:
        logger.warning(
            "No rendered MD found in /workdir/outputs/ — skipping conversion",
            _name="NOLIA_FUNDING_ASSESS_NO_MD",
            phase="pipeline",
        )

    # ── Pull applicant + decision + score summary out of /workdir/tmp/ ────
    # Phase 3 extended /workdir/tmp/applicant.json with a `decision` block
    # and (for scored Funds) a top-level `score` field. Both ship in
    # _result.json below. _applicant.json stays Phase-1-shaped — the
    # frontend (V2AppsController) reads _result.json once the run is
    # complete, and _applicant.json is only consulted when _result.json's
    # applicant.name is missing, so re-publishing the preview adds nothing.
    applicant_info, needs_review_flag, decision_info, score_info = (
        _read_applicant_summary()
    )

    # ── Done ────────────────────────────────────────────────────────────────
    emit("complete", "Assessment complete")
    pipeline_duration = int((time.monotonic() - pipeline_start) * 1000)
    total_usage["duration_ms"] = pipeline_duration

    final_text = all_steps[-1].get("text", "") if all_steps else ""

    logger.info(
        "Nolia Funding assess pipeline completed",
        _name="NOLIA_FUNDING_ASSESS_PIPELINE_COMPLETE",
        phase="pipeline",
        total_steps=len(all_steps),
        total_turns=total_usage["num_turns"],
        total_cost=total_usage["total_cost_usd"],
        duration_ms=pipeline_duration,
        needs_review=needs_review_flag,
    )

    result = {
        "status": "completed",
        "text": final_text,
        "artifacts": all_artifacts,
        "usage": total_usage,
        "steps": all_steps,
        "pipeline": {
            "name": "nolia-funding-assess",
            "version": "1.0",
            "applicant_id": applicant_id,
            "global_kb_id": global_kb_id,
            "funding_kb_id": funding_kb_id,
            "client_name": client_name,
        },
        "applicant": applicant_info,
        "decision": decision_info,
        "score": score_info,
        "needs_review": needs_review_flag,
    }

    # Safety-net write of _result.json + S3 sync
    from ...s3_workspace import sync_to_s3, write_result_to_s3

    try:
        sync_to_s3(user_sub, conversation_id, s3_prefix=s3_prefix_fmt)
        write_result_to_s3(
            user_sub,
            conversation_id,
            result,
            s3_prefix=parent_config.s3_prefix_template,
        )
        logger.info(
            "Funding assess orchestrator wrote result to S3",
            _name="NOLIA_FUNDING_ASSESS_RESULT_WRITTEN",
            phase="pipeline",
            conversation_id=conversation_id,
        )
    except Exception as e:
        logger.error(
            "Funding assess orchestrator failed to write result",
            _name="NOLIA_FUNDING_ASSESS_RESULT_WRITE_ERROR",
            phase="pipeline",
            error=str(e),
        )

    return result


# ─── Helpers ─────────────────────────────────────────────────────────────────


def _find_rendered_assessment():
    """Find the Phase 3 rendered MD in /workdir/outputs/.

    Phase 3 writes a file named ``Assessment_<name>.md`` — we glob to find
    it without needing to know the applicant name. If multiple match (e.g.
    due to retries), pick the most recently modified.
    """
    if not OUTPUTS_DIR.exists():
        return None
    candidates = sorted(
        OUTPUTS_DIR.glob("Assessment_*.md"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    return candidates[0] if candidates else None


def _write_applicant_preview_to_s3(
    *,
    user_sub: str,
    conversation_id: str,
    s3_prefix: str,
    applicant_id: str,
) -> None:
    """Publish the Phase-1 applicant summary to S3 mid-run.

    Called immediately after Phase 1 (extract) succeeds and before Phase 2
    starts. Writes ``{s3_prefix}/_applicant.json`` to the outputs bucket so
    the frontend can poll for it while Phase 2 + Phase 3 are still running
    (~2 additional minutes) and update the activity-table row with the
    real applicant name instead of a runId placeholder.

    Payload shape::

        {
          "version": "1.0",
          "phase": "extract_complete",
          "published_at": "2026-04-19T10:34:12Z",
          "applicant_id": "APP-A1B2C3" | "",    # cosmetic, from metadata
          "applicant": {                         # from applicant.json
            "id": "APP-A1B2C3" | null,
            "name": "Ella Jackson" | null,
            "selected_fund": "...",
            "requested_amount": {...}
          },
          "needs_review": false,
          "review_reason": null | "..."
        }

    Small file (~300 bytes). Fails soft — if applicant.json is missing or
    OUTPUTS_BUCKET isn't set, this just logs + returns. Never blocks the
    pipeline.
    """
    import json as _json
    import os

    from ...s3_workspace import _get_s3_client

    outputs_bucket = os.environ.get("OUTPUTS_BUCKET_NAME", "")
    if not outputs_bucket:
        logger.warning(
            "OUTPUTS_BUCKET_NAME not set — skipping applicant preview publish",
            _name="NOLIA_FUNDING_ASSESS_PREVIEW_NO_BUCKET",
            phase="pipeline",
        )
        return

    # Decision and score are always None here — this helper only runs after
    # Phase 1, before Phase 3 has written those blocks. Unpack but discard.
    (
        applicant_summary,
        needs_review_flag,
        _decision_unused,
        _score_unused,
    ) = _read_applicant_summary()
    if applicant_summary is None:
        logger.warning(
            "Phase 1 produced no parseable applicant.json — no preview to publish",
            _name="NOLIA_FUNDING_ASSESS_PREVIEW_NO_APPLICANT",
            phase="pipeline",
        )
        return

    review_reason = None
    try:
        tmp_path = TMP_DIR / "applicant.json"
        if tmp_path.exists():
            data = _json.loads(tmp_path.read_text())
            review_reason = data.get("review_reason")
    except Exception:
        pass

    payload = {
        "version": "1.0",
        "phase": "extract_complete",
        "published_at": datetime.now(timezone.utc).isoformat(),
        "applicant_id": applicant_id or "",
        "applicant": applicant_summary,
        "needs_review": needs_review_flag,
        "review_reason": review_reason,
    }

    preview_key = f"{s3_prefix.rstrip('/')}/_applicant.json"
    try:
        s3 = _get_s3_client()
        s3.put_object(
            Bucket=outputs_bucket,
            Key=preview_key,
            Body=_json.dumps(payload, default=str).encode("utf-8"),
            ContentType="application/json",
        )
        logger.info(
            "Applicant preview published",
            _name="NOLIA_FUNDING_ASSESS_PREVIEW_WRITTEN",
            phase="pipeline",
            s3_key=preview_key,
            needs_review=needs_review_flag,
        )
    except Exception as e:
        logger.warning(
            "Failed to publish applicant preview — pipeline continues",
            _name="NOLIA_FUNDING_ASSESS_PREVIEW_WRITE_FAIL",
            phase="pipeline",
            error=str(e),
        )


def _read_applicant_summary() -> (
    tuple[Optional[dict], bool, Optional[dict], Optional[dict]]
):
    """Read /workdir/tmp/applicant.json for the result-level blocks.

    Returns ``(applicant_info, needs_review_flag, decision_info, score_info)``.
    All four default to ``None`` / ``False`` / ``None`` / ``None`` if the file
    is missing or unparseable.

    Schema assumed (per ``prompts/assess_extract.py`` + ``prompts/assess_render.py``):
        { "version": "1.0",
          "applicant": { "name": ..., "selected_fund": ..., "requested_amount": ... },
          "applicant_id": ...,
          "requires_manual_review": bool,
          "decision": {                          # added by Phase 3 (render)
              "status": "APPROVED" | "DECLINED" | "AWAITING_MORE_INFO",
              "summary": "...",
              "recommended_amount": {...} | null,
              "blocking_reasons": [...],
              "next_action": "...",
              "action_by": "..."
          } | absent,
          "score": {"value": int, "max": int} | absent | null,   # Phase 3, scored Funds only
          ... }

    ``decision`` and ``score`` are absent when called from the Phase-1 mid-run
    preview (they haven't been written yet). They're populated by the end of
    Phase 3 — ``score`` only when the Fund uses an aggregate scoring rubric.

    A schema mismatch is logged via ``NOLIA_FUNDING_ASSESS_APPLICANT_SCHEMA_MISMATCH``
    so we can spot drift between the prompt instructions and the agent's output.
    """
    import json

    applicant_path = TMP_DIR / "applicant.json"
    if not applicant_path.exists():
        return None, False, None, None
    try:
        data = json.loads(applicant_path.read_text())
    except Exception as e:
        logger.warning(
            "Failed to parse applicant.json for result summary",
            _name="NOLIA_FUNDING_ASSESS_APPLICANT_PARSE_FAIL",
            error=str(e),
        )
        return None, False, None, None

    applicant = data.get("applicant") or {}
    if not applicant.get("name"):
        logger.warning(
            "applicant.json missing expected schema — `applicant.name` not found",
            _name="NOLIA_FUNDING_ASSESS_APPLICANT_SCHEMA_MISMATCH",
            top_level_keys=sorted(data.keys()),
            applicant_keys=(
                sorted(applicant.keys()) if isinstance(applicant, dict) else []
            ),
        )
    summary = {
        "id": data.get("applicant_id"),
        "name": applicant.get("name"),
        "selected_fund": applicant.get("selected_fund"),
        "requested_amount": applicant.get("requested_amount"),
    }
    needs_review = bool(data.get("requires_manual_review", False))

    decision = data.get("decision")
    if decision is not None and not isinstance(decision, dict):
        logger.warning(
            "applicant.json `decision` present but not a dict",
            _name="NOLIA_FUNDING_ASSESS_DECISION_SCHEMA_MISMATCH",
            decision_type=type(decision).__name__,
        )
        decision = None
    elif isinstance(decision, dict) and not decision.get("status"):
        logger.warning(
            "applicant.json `decision` missing `status`",
            _name="NOLIA_FUNDING_ASSESS_DECISION_SCHEMA_MISMATCH",
            decision_keys=sorted(decision.keys()),
        )

    score = data.get("score")
    if score is not None:
        if not isinstance(score, dict) or "value" not in score or "max" not in score:
            logger.warning(
                "applicant.json `score` present but malformed",
                _name="NOLIA_FUNDING_ASSESS_SCORE_SCHEMA_MISMATCH",
                score_type=type(score).__name__,
                score_keys=(sorted(score.keys()) if isinstance(score, dict) else []),
            )
            score = None

    return summary, needs_review, decision, score


# ─── Step runner (mirrors rules_orchestrator's _run_step) ────────────────────


async def _run_step(
    step_type_id: str,
    step_suffix: str,
    *,
    prompt: str,
    user_sub: str,
    conversation_id: str,
    is_first_step: bool = False,
    timezone: Optional[str] = None,
    user_email: Optional[str] = None,
    today_string: Optional[str] = None,
    available_kbs: Optional[list[dict]] = None,
    enabled_tools: Optional[list[str]] = None,
    model_id: Optional[str] = None,
    request_id: Optional[str] = None,
    attached_files: Optional[list[dict]] = None,
    attached_folders: Optional[list[dict]] = None,
    kb_listings: Optional[dict[str, dict]] = None,
    external_user_id: Optional[str] = None,
    enabled_integrations: Optional[list[str]] = None,
) -> dict[str, Any]:
    """Run a single pipeline step via the Claude Agent SDK."""
    from ...sdk_config import LOCAL_ROOT
    from ...sdk_runner import run_claude_sdk
    from ...workspace import setup_agent_tools
    from .. import ALWAYS_COPY, TOOL_FILE_MAP

    step_config = get_agent_type_config(step_type_id)
    step_conversation_id = f"{conversation_id}-step-{step_suffix}"
    step_request_id = request_id or str(uuid.uuid4())

    step_system_dir = LOCAL_ROOT / ".system" / f"step-{step_suffix}"
    step_system_dir.mkdir(parents=True, exist_ok=True)

    step_kbs = available_kbs
    if step_config.restrict_kbs:
        step_kbs = step_config.default_kbs or []

    step_integrations = enabled_integrations
    if step_config.restrict_integrations:
        step_integrations = step_config.default_integrations or []

    step_external_user_id = external_user_id if step_integrations else None

    step_kb_listings = kb_listings
    if step_kbs != available_kbs:
        step_kb_listings = None

    setup_agent_tools(
        enabled_numa_tools=step_config.enabled_numa_tools,
        tools_source_dirs=step_config.tools_source_dirs,
        tool_file_map=TOOL_FILE_MAP,
        always_copy=ALWAYS_COPY,
    )

    logger.info(
        "Running funding assess pipeline step",
        _name="NOLIA_FUNDING_ASSESS_STEP_START",
        phase="pipeline",
        step_type=step_type_id,
        step_conversation_id=step_conversation_id,
    )

    try:
        result = await run_claude_sdk(
            conversation_id=step_conversation_id,
            prompt=prompt,
            user_sub=user_sub,
            timezone_str=timezone,
            user_email=user_email,
            today_string=today_string,
            available_kbs=step_kbs,
            enabled_tools=enabled_tools,
            is_cold_start=True,
            attached_files=attached_files if is_first_step else [],
            attached_folders=attached_folders if is_first_step else [],
            original_prompt=prompt,
            model_id=model_id,
            kb_listings=step_kb_listings,
            request_id=step_request_id,
            agent_config=None,
            external_user_id=step_external_user_id,
            enabled_integrations=step_integrations,
            agent_type_config=step_config,
            system_dir=step_system_dir,
        )
    except Exception as e:
        logger.error(
            "Funding assess pipeline step exception",
            _name="NOLIA_FUNDING_ASSESS_STEP_EXCEPTION",
            phase="pipeline",
            step_type=step_type_id,
            error=str(e),
            exc_info=True,
        )
        return {
            "status": "error",
            "text": "",
            "artifacts": [],
            "usage": {},
            "error": str(e),
        }
    finally:
        shutil.rmtree(step_system_dir, ignore_errors=True)

    logger.info(
        "Funding assess pipeline step completed",
        _name="NOLIA_FUNDING_ASSESS_STEP_COMPLETE",
        phase="pipeline",
        step_type=step_type_id,
        status=result.get("status", "completed"),
        turns=result.get("usage", {}).get("num_turns", 0),
    )

    return result


def _build_error_result(
    steps: list[dict],
    artifacts: list[dict],
    usage: dict,
    error_msg: str,
    *,
    applicant_id: str = "",
) -> dict[str, Any]:
    return {
        "status": "error",
        "text": "",
        "artifacts": artifacts,
        "usage": usage,
        "error": error_msg,
        "steps": steps,
        "applicant": {"id": applicant_id, "name": None},
        "decision": None,
        "score": None,
        "needs_review": True,
    }
