"""Pipeline orchestrator for Nolia Funding rules generation.

Handles BOTH Funding KBs and Global KBs via a ``kb_category`` metadata
field. Dispatches to category-specific phase agent types + filenames:

    Funding KBs (``kb_category="funding"``, default):
        Phase 1: Extract        — nolia-funding-rules-extract
        Phase 2: Review         — nolia-funding-rules-review
        Phase 3: Second Review  — nolia-funding-rules-second-review
        Draft:     /workdir/tmp/extracted_rules.md
        Final:     /workdir/outputs/funding-rules.md
        S3 key:    documents/kb-{kb_id}/funding-rules.md

    Global KBs (``kb_category="global"``):
        Phase 1: Extract        — nolia-funding-rules-extract-global
        Phase 2: Review         — nolia-funding-rules-review-global
        Phase 3: Second Review  — nolia-funding-rules-second-review-global
        Draft:     /workdir/tmp/extracted_global_rules.md
        Final:     /workdir/outputs/global-rules.md
        S3 key:    documents/kb-{kb_id}/global-rules.md

Phase 3 is a targeted structural / completeness audit — it verifies the
mandatory closing sections (Decision Framework, Critical Rules Summary,
Strategic Framework), 100% manifest coverage, resolved F-ID cross-refs,
and per-rule structural integrity. It edits the file in place and is
significantly shorter than Phase 2 by design.

Pre-pipeline: ``setup_funding_rules_workspace()`` downloads the KB's
input files into ``/workdir/knowledge-bases/``. For Funding KBs it
pulls the 4 subfolders (application-form, selection-criteria, good-examples,
templates) plus the supporting-data-manifest.json; for Global KBs it
pulls the single ``documents/`` folder.

Post-pipeline: uploads the finalised rules file back to its S3 key.

Pattern mirrors ``nolia/rules_orchestrator.py`` — shared helpers reused
inline where pragmatic.
"""

import os
import shutil
import time
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

import boto3
import structlog

from ..base import AgentTypeConfig
from ..registry import get_agent_type_config
from .workspace_setup import (
    OUTPUTS_DIR,
    TMP_DIR,
    pre_extract_kb_documents,
    setup_funding_rules_workspace,
)

logger = structlog.get_logger()

DATA_BUCKET = os.environ.get("DATA_BUCKET_NAME", "")
AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")

# Per-category dispatch — keeps one frontend-facing agent type
# (``nolia-funding-rules-generator``) but routes to the appropriate
# phase agents + filenames based on ``metadata.kb_category``.
_CATEGORY_CONFIG = {
    "funding": {
        "extract_type_id": "nolia-funding-rules-extract",
        "review_type_id": "nolia-funding-rules-review",
        "second_review_type_id": "nolia-funding-rules-second-review",
        "draft_filename": "extracted_rules.md",
        "final_filename": "funding-rules.md",
        "rule_marker": "**F-",
    },
    "global": {
        "extract_type_id": "nolia-funding-rules-extract-global",
        "review_type_id": "nolia-funding-rules-review-global",
        "second_review_type_id": "nolia-funding-rules-second-review-global",
        "draft_filename": "extracted_global_rules.md",
        "final_filename": "global-rules.md",
        "rule_marker": "**G-",
    },
}


def _emit_progress(
    user_sub: str,
    conversation_id: str,
    s3_prefix: str | None,
    events: list[dict],
    phase: str,
    message: str,
) -> None:
    """Append a progress event and write _progress.json to S3."""
    from ...s3_workspace import write_progress_to_s3

    events.append(
        {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "phase": phase,
            "message": message,
        }
    )
    write_progress_to_s3(user_sub, conversation_id, events, s3_prefix=s3_prefix)


async def run_nolia_funding_rules_pipeline(
    prompt: str,
    user_sub: str,
    conversation_id: str,
    parent_config: AgentTypeConfig,
    *,
    timezone: Optional[str] = None,
    user_email: Optional[str] = None,
    today_string: Optional[str] = None,
    available_kbs: Optional[list[dict]] = None,
    enabled_tools: Optional[list[str]] = None,
    model_id: Optional[str] = None,
    request_id: Optional[str] = None,
    attached_files: Optional[list[dict]] = None,
    attached_folders: Optional[list[dict]] = None,
    kb_listings: Optional[dict[str, dict]] = None,
    external_user_id: Optional[str] = None,
    enabled_integrations: Optional[list[str]] = None,
    request_metadata: Optional[dict] = None,
    **_kwargs: Any,
) -> dict[str, Any]:
    """Run the Nolia Funding rules generation pipeline.

    Args:
        prompt: User prompt (usually auto-generated by the trigger).
        user_sub: Cognito user sub.
        conversation_id: Base conversation / run ID.
        parent_config: The nolia-funding-rules-generator AgentTypeConfig.
        request_metadata: Must contain:
            kb_id: UUID of the KB
            kb_name: Display name of the KB
            kb_category: "funding" (default) or "global" — dispatches to the
                appropriate phase agents + filenames.
        **_kwargs: Standard pipeline kwargs forwarded to run_claude_sdk.

    Returns:
        dict with status, text, artifacts, usage, steps.
    """
    pipeline_start = time.monotonic()
    metadata = request_metadata or {}
    kb_id = metadata.get("kb_id", "")
    kb_name = metadata.get("kb_name", "Unknown Fund")
    kb_category = metadata.get("kb_category", "funding")
    client_name = metadata.get("client_name", "")

    if kb_category not in _CATEGORY_CONFIG:
        logger.warning(
            "Unknown kb_category — falling back to 'funding'",
            _name="NOLIA_FUNDING_RULES_UNKNOWN_CATEGORY",
            phase="pipeline",
            kb_category=kb_category,
        )
        kb_category = "funding"

    cat_config = _CATEGORY_CONFIG[kb_category]
    extract_type_id = cat_config["extract_type_id"]
    review_type_id = cat_config["review_type_id"]
    second_review_type_id = cat_config["second_review_type_id"]
    draft_filename = cat_config["draft_filename"]
    final_filename = cat_config["final_filename"]
    rule_marker = cat_config["rule_marker"]

    logger.info(
        "Starting Nolia Funding rules pipeline",
        _name="NOLIA_FUNDING_RULES_PIPELINE_START",
        phase="pipeline",
        kb_id=kb_id,
        kb_name=kb_name,
        kb_category=kb_category,
        client_name=client_name,
        conversation_id=conversation_id,
    )

    s3_prefix_fmt = parent_config.s3_prefix_template.format(
        user_sub=user_sub,
        conversation_id=conversation_id,
    )
    progress_events: list[dict] = []

    def emit(phase: str, message: str) -> None:
        _emit_progress(
            user_sub, conversation_id, s3_prefix_fmt, progress_events, phase, message
        )

    # ── Pre-pipeline: download KB inputs ────────────────────────────────────
    emit("download", f"Loading '{kb_name}' source documents...")
    await setup_funding_rules_workspace(
        user_sub,
        conversation_id,
        kb_id=kb_id,
        kb_name=kb_name,
        kb_category=kb_category,
    )

    # ── Pre-pipeline: extract every PDF/DOCX in the KB to JSON sidecars ─────
    # Sidecars land next to originals in S3 (cached for every future
    # assessment) and locally next to the rules-relevant originals (so the
    # rules agent below can read JSON instead of raw PDFs). Non-fatal —
    # rules.md still gets written if extraction trips, and assessments will
    # fall back to per-run extraction (slower but functional).
    emit("kb-cache", "Pre-extracting KB documents for fast assessment...")
    try:
        kb_extract_summary = await pre_extract_kb_documents(kb_id, kb_category)
        logger.info(
            "KB pre-extraction complete",
            _name="NOLIA_FUNDING_RULES_KB_EXTRACT_COMPLETE",
            phase="pipeline",
            kb_id=kb_id,
            kb_category=kb_category,
            extracted=kb_extract_summary.get("extracted", 0),
            failed=kb_extract_summary.get("failed", 0),
        )
    except Exception as e:
        logger.warning(
            "KB pre-extraction failed — assessments will fall back to per-run extraction",
            _name="NOLIA_FUNDING_RULES_KB_EXTRACT_FAIL",
            phase="pipeline",
            error=str(e),
        )

    # ── Step-specific user prompts (per-category) ──────────────────────────
    if kb_category == "global":
        user_context = (
            f"Generate an ORGANISATION-WIDE (Global) assessment rulebook "
            f"for the '{kb_name}' knowledge base. Read the policy documents "
            f"in `/workdir/knowledge-bases/documents/` and produce a "
            f"self-contained, cited set of rules that apply across every "
            f"Fund, Grant, and Scholarship."
        )
        extract_prompt = (
            f"{user_context}\n\n"
            "You are running Phase 1 (Extract Global Rules). Read every "
            "document in `/workdir/knowledge-bases/documents/` and extract "
            "the full org-wide rule set. Write your draft to "
            f"`/workdir/tmp/{draft_filename}`."
        )
        review_prompt = (
            f"{user_context}\n\n"
            "You are running Phase 2 (Review Global Rules). Phase 1 "
            f"produced a draft at `/workdir/tmp/{draft_filename}`. Verify "
            "it against the source documents, correct citations, add "
            "missed rules, deduplicate, remove any fund-specific rules "
            "that don't belong at Global level, and write the final file "
            f"to `/workdir/outputs/{final_filename}`."
        )
        second_review_prompt = (
            f"{user_context}\n\n"
            "You are running Phase 3 (Second Review — Structural Audit). "
            f"Phase 2 produced the final rulebook at "
            f"`/workdir/outputs/{final_filename}`. Run the Global-KB "
            "audit checklist in your system prompt and fix any defects in "
            "place. Append the Phase 3 Audit block near the top of the "
            "file (right after the Phase 2 Corrections block) and stop "
            "when the checklist passes."
        )
    else:
        user_context = (
            f"Generate an assessment rulebook for the '{kb_name}' Funding "
            f"knowledge base. Read the selection-criteria documents "
            f"(policy, rubric, scorecard), application form, output "
            f"template, and supporting-data-manifest.json in "
            f"`/workdir/knowledge-bases/` and produce a self-contained, "
            f"cited set of rules that a downstream assessor can use to "
            f"evaluate applicants. Every file listed in the manifest must "
            f"also become its own rule describing how the assessor "
            f"consults it."
        )
        extract_prompt = (
            f"{user_context}\n\n"
            "You are running Phase 1 (Extract Rules). Read every document "
            "in `/workdir/knowledge-bases/` (selection-criteria/, "
            "application-form/, templates/, good-examples/ if present) "
            "and extract the full rule set. Also read "
            "`/workdir/knowledge-bases/supporting-data-manifest.json` if "
            "present and emit one rule per listed file describing the "
            "file's purpose (verbatim from the manifest description) and "
            "how/when the assessor consults it. Write your draft to "
            f"`/workdir/tmp/{draft_filename}`."
        )
        review_prompt = (
            f"{user_context}\n\n"
            "You are running Phase 2 (Review Rules). Phase 1 produced a "
            f"draft at `/workdir/tmp/{draft_filename}`. Verify it against "
            "the source documents, correct citations, add missed rules, "
            "deduplicate, and write the final file to "
            f"`/workdir/outputs/{final_filename}`. Explicitly verify that "
            "every file listed in `supporting-data-manifest.json` is "
            "covered by a dedicated rule (or equivalent entry in a "
            "Data Sources Reference section) — add any missing coverage. "
            "End the file with the three mandatory closing sections per "
            "your system prompt (Strategic Framework where applicable, "
            "Decision Framework, Critical Rules Summary)."
        )
        second_review_prompt = (
            f"{user_context}\n\n"
            "You are running Phase 3 (Second Review — Structural Audit). "
            f"Phase 2 produced the final rulebook at "
            f"`/workdir/outputs/{final_filename}`. Run the audit "
            "checklist in your system prompt (mandatory closing sections, "
            "100% manifest coverage, resolved F-ID cross-references, "
            "per-rule structural integrity, Phase 2 log and Gap appendix, "
            "Decision Framework consistency with atomic rules) and fix "
            "any defects in place. Append the Phase 3 Audit block near "
            "the top of the file (right after the Phase 2 Corrections "
            "block) and stop when the checklist passes."
        )

    step_kwargs = dict(
        prompt=prompt,  # default, overridden per step
        user_sub=user_sub,
        conversation_id=conversation_id,
        timezone=timezone,
        user_email=user_email,
        today_string=today_string,
        available_kbs=available_kbs,
        enabled_tools=enabled_tools,
        request_id=request_id or str(uuid.uuid4()),
        attached_files=attached_files,
        attached_folders=attached_folders,
        kb_listings=kb_listings,
        external_user_id=external_user_id,
        enabled_integrations=enabled_integrations,
    )

    all_steps: list[dict[str, Any]] = []
    all_artifacts: list[dict] = []
    total_usage: dict[str, Any] = {
        "num_turns": 0,
        "total_cost_usd": 0.0,
        "duration_ms": 0,
    }

    def _accumulate(result: dict[str, Any], step_name: str) -> dict[str, Any]:
        usage = result.get("usage", {})
        all_steps.append(
            {
                "step": step_name,
                "step_number": len(all_steps) + 1,
                "status": result.get("status", "completed"),
                "text": result.get("text", ""),
                "usage": usage,
            }
        )
        all_artifacts.extend(result.get("artifacts", []))
        total_usage["num_turns"] += usage.get("num_turns", 0)
        total_usage["total_cost_usd"] += usage.get("total_cost_usd", 0.0)
        total_usage["duration_ms"] += usage.get("duration_ms", 0)
        return result

    def _check_error(result: dict[str, Any], step_name: str) -> bool:
        if result.get("status") == "error":
            logger.error(
                "Funding rules pipeline step failed",
                _name="NOLIA_FUNDING_RULES_STEP_ERROR",
                phase="pipeline",
                step=step_name,
                error=result.get("error", "unknown"),
            )
            return True
        return False

    # ── Phase 1: Extract ────────────────────────────────────────────────────
    emit("extract", "Reading source documents and drafting criteria...")
    extract_result = _accumulate(
        await _run_step(
            extract_type_id,
            "extract",
            is_first_step=True,
            **{**step_kwargs, "prompt": extract_prompt},
        ),
        extract_type_id,
    )
    if _check_error(extract_result, extract_type_id):
        return _build_error_result(
            all_steps, all_artifacts, total_usage, "Phase 1 (Extract) failed"
        )

    # ── Phase 2: Review ─────────────────────────────────────────────────────
    emit("review", "Reviewing draft against source documents...")
    review_result = _accumulate(
        await _run_step(
            review_type_id,
            "review",
            **{**step_kwargs, "prompt": review_prompt},
        ),
        review_type_id,
    )
    if _check_error(review_result, review_type_id):
        return _build_error_result(
            all_steps, all_artifacts, total_usage, "Phase 2 (Review) failed"
        )

    # ── Fallback: if Phase 2 didn't write the file, copy from Phase 1 ──────
    rules_local_path = OUTPUTS_DIR / final_filename
    extracted_path = TMP_DIR / draft_filename
    if not rules_local_path.exists() and extracted_path.exists():
        logger.warning(
            "Phase 2 did not write final rules file — falling back to Phase 1 output",
            _name="NOLIA_FUNDING_RULES_FALLBACK",
            phase="pipeline",
            source=str(extracted_path),
            dest=str(rules_local_path),
        )
        shutil.copy2(str(extracted_path), str(rules_local_path))

    # ── Phase 3: Second Review (targeted structural audit) ──────────────────
    # Non-blocking: if Phase 3 errors, we still upload the Phase 2 output.
    # Phase 3 edits `/workdir/outputs/{final_filename}` in place to fix
    # missing closing sections, broken F-ID cross-refs, incomplete manifest
    # coverage, and malformed rules.
    if rules_local_path.exists():
        emit("second-review", "Auditing criteria for completeness...")
        second_review_result = _accumulate(
            await _run_step(
                second_review_type_id,
                "second-review",
                **{**step_kwargs, "prompt": second_review_prompt},
            ),
            second_review_type_id,
        )
        if _check_error(second_review_result, second_review_type_id):
            logger.warning(
                "Phase 3 (Second Review) failed — continuing with Phase 2 output",
                _name="NOLIA_FUNDING_RULES_PHASE3_NONBLOCKING_FAIL",
                phase="pipeline",
                error=second_review_result.get("error", "unknown"),
            )
    else:
        logger.warning(
            "Skipping Phase 3 — no rules file to audit",
            _name="NOLIA_FUNDING_RULES_PHASE3_SKIPPED",
            phase="pipeline",
            rules_path=str(rules_local_path),
        )

    # ── Sanity check: warn on suspiciously small or rule-free output ────────
    # Doesn't block upload — we want the output saved even when imperfect.
    # Signals for the reviewer: CloudWatch filter on
    # NOLIA_FUNDING_RULES_QUALITY_WARN to catch truncations early.
    if rules_local_path.exists():
        rules_text = rules_local_path.read_text()
        rules_bytes = len(rules_text.encode("utf-8"))
        # Count lines that look like rule definitions — "**F-" / "**G-"
        # pattern per the prompt spec. Cheap proxy for "did we produce
        # rules?"
        rule_marker_count = rules_text.count(rule_marker)
        if rules_bytes < 1024 or rule_marker_count < 5:
            logger.warning(
                "Generated rules file looks suspiciously short or rule-free",
                _name="NOLIA_FUNDING_RULES_QUALITY_WARN",
                phase="pipeline",
                kb_category=kb_category,
                rules_bytes=rules_bytes,
                rule_marker_count=rule_marker_count,
                rules_path=str(rules_local_path),
            )
        else:
            logger.info(
                "Generated rules file passed basic quality check",
                _name="NOLIA_FUNDING_RULES_QUALITY_OK",
                phase="pipeline",
                kb_category=kb_category,
                rules_bytes=rules_bytes,
                rule_marker_count=rule_marker_count,
            )

    # ── Post-pipeline: upload rules file to the KB's S3 prefix ─────────────
    emit("upload", "Saving criteria to knowledge base...")

    if rules_local_path.exists() and DATA_BUCKET and kb_id:
        rules_s3_key = f"documents/kb-{kb_id}/{final_filename}"
        try:
            s3 = boto3.client("s3", region_name=AWS_REGION)
            s3.upload_file(
                str(rules_local_path),
                DATA_BUCKET,
                rules_s3_key,
                ExtraArgs={"ContentType": "text/markdown"},
            )
            all_artifacts.append({"type": "file", "path": f"outputs/{final_filename}"})
            logger.info(
                "Uploaded rules file to KB",
                _name="NOLIA_FUNDING_RULES_UPLOADED",
                phase="pipeline",
                kb_category=kb_category,
                s3_key=rules_s3_key,
            )
        except Exception as e:
            logger.error(
                "Failed to upload funding-rules.md",
                _name="NOLIA_FUNDING_RULES_UPLOAD_ERROR",
                phase="pipeline",
                error=str(e),
            )
    else:
        logger.warning(
            "Rules file not found or missing config — skipping upload",
            _name="NOLIA_FUNDING_RULES_NO_UPLOAD",
            phase="pipeline",
            rules_path=str(rules_local_path),
            exists=rules_local_path.exists(),
            has_data_bucket=bool(DATA_BUCKET),
            has_kb_id=bool(kb_id),
        )

    # ── Done ────────────────────────────────────────────────────────────────
    emit("complete", "Criteria ready")
    pipeline_duration = int((time.monotonic() - pipeline_start) * 1000)
    total_usage["duration_ms"] = pipeline_duration

    final_text = all_steps[-1].get("text", "") if all_steps else ""

    logger.info(
        "Nolia Funding rules pipeline completed",
        _name="NOLIA_FUNDING_RULES_PIPELINE_COMPLETE",
        phase="pipeline",
        total_steps=len(all_steps),
        total_turns=total_usage["num_turns"],
        total_cost=total_usage["total_cost_usd"],
        duration_ms=pipeline_duration,
    )

    result = {
        "status": "completed",
        "text": final_text,
        "artifacts": all_artifacts,
        "usage": total_usage,
        "steps": all_steps,
        "pipeline": {
            "name": "nolia-funding-rules-generator",
            "version": "1.1",  # Added Phase 3 Second Review + mandatory closing sections
            "kb_id": kb_id,
            "kb_name": kb_name,
            "kb_category": kb_category,
            "client_name": client_name,
        },
    }

    # Safety-net write of _result.json (same pattern as nolia/orchestrator.py)
    from ...s3_workspace import sync_to_s3, write_result_to_s3

    try:
        sync_to_s3(user_sub, conversation_id, s3_prefix=s3_prefix_fmt)
        write_result_to_s3(
            user_sub,
            conversation_id,
            result,
            s3_prefix=parent_config.s3_prefix_template,
        )
        logger.info(
            "Funding rules orchestrator wrote result to S3",
            _name="NOLIA_FUNDING_RULES_RESULT_WRITTEN",
            phase="pipeline",
            conversation_id=conversation_id,
        )
    except Exception as e:
        logger.error(
            "Funding rules orchestrator failed to write result",
            _name="NOLIA_FUNDING_RULES_RESULT_WRITE_ERROR",
            phase="pipeline",
            error=str(e),
        )

    return result


# ─── Step runner (mirrors nolia/rules_orchestrator.py's _run_step) ──────────


async def _run_step(
    step_type_id: str,
    step_suffix: str,
    *,
    prompt: str,
    user_sub: str,
    conversation_id: str,
    is_first_step: bool = False,
    timezone: Optional[str] = None,
    user_email: Optional[str] = None,
    today_string: Optional[str] = None,
    available_kbs: Optional[list[dict]] = None,
    enabled_tools: Optional[list[str]] = None,
    model_id: Optional[str] = None,
    request_id: Optional[str] = None,
    attached_files: Optional[list[dict]] = None,
    attached_folders: Optional[list[dict]] = None,
    kb_listings: Optional[dict[str, dict]] = None,
    external_user_id: Optional[str] = None,
    enabled_integrations: Optional[list[str]] = None,
) -> dict[str, Any]:
    """Run a single pipeline step via the Claude Agent SDK.

    Same shape as ``nolia/rules_orchestrator.py::_run_step``. Duplicated
    intentionally to keep product boundaries clean — if the two diverge in
    the future (e.g. funding needs different session/tool setup), they can
    evolve independently.
    """
    from ...sdk_config import LOCAL_ROOT
    from ...sdk_runner import run_claude_sdk
    from ...workspace import setup_agent_tools
    from .. import ALWAYS_COPY, TOOL_FILE_MAP

    step_config = get_agent_type_config(step_type_id)
    step_conversation_id = f"{conversation_id}-step-{step_suffix}"
    step_request_id = request_id or str(uuid.uuid4())

    step_system_dir = LOCAL_ROOT / ".system" / f"step-{step_suffix}"
    step_system_dir.mkdir(parents=True, exist_ok=True)

    step_kbs = available_kbs
    if step_config.restrict_kbs:
        step_kbs = step_config.default_kbs or []

    step_integrations = enabled_integrations
    if step_config.restrict_integrations:
        step_integrations = step_config.default_integrations or []

    step_external_user_id = external_user_id if step_integrations else None

    step_kb_listings = kb_listings
    if step_kbs != available_kbs:
        step_kb_listings = None

    setup_agent_tools(
        enabled_numa_tools=step_config.enabled_numa_tools,
        tools_source_dirs=step_config.tools_source_dirs,
        tool_file_map=TOOL_FILE_MAP,
        always_copy=ALWAYS_COPY,
    )

    logger.info(
        "Running funding rules pipeline step",
        _name="NOLIA_FUNDING_RULES_STEP_START",
        phase="pipeline",
        step_type=step_type_id,
        step_conversation_id=step_conversation_id,
    )

    try:
        result = await run_claude_sdk(
            conversation_id=step_conversation_id,
            prompt=prompt,
            user_sub=user_sub,
            timezone_str=timezone,
            user_email=user_email,
            today_string=today_string,
            available_kbs=step_kbs,
            enabled_tools=enabled_tools,
            is_cold_start=True,
            attached_files=attached_files if is_first_step else [],
            attached_folders=attached_folders if is_first_step else [],
            original_prompt=prompt,
            model_id=model_id,
            kb_listings=step_kb_listings,
            request_id=step_request_id,
            agent_config=None,
            external_user_id=step_external_user_id,
            enabled_integrations=step_integrations,
            agent_type_config=step_config,
            system_dir=step_system_dir,
        )
    except Exception as e:
        logger.error(
            "Funding rules pipeline step exception",
            _name="NOLIA_FUNDING_RULES_STEP_EXCEPTION",
            phase="pipeline",
            step_type=step_type_id,
            error=str(e),
            exc_info=True,
        )
        return {
            "status": "error",
            "text": "",
            "artifacts": [],
            "usage": {},
            "error": str(e),
        }
    finally:
        shutil.rmtree(step_system_dir, ignore_errors=True)

    logger.info(
        "Funding rules pipeline step completed",
        _name="NOLIA_FUNDING_RULES_STEP_COMPLETE",
        phase="pipeline",
        step_type=step_type_id,
        status=result.get("status", "completed"),
        turns=result.get("usage", {}).get("num_turns", 0),
    )

    return result


def _build_error_result(
    steps: list[dict],
    artifacts: list[dict],
    usage: dict,
    error_msg: str,
) -> dict[str, Any]:
    return {
        "status": "error",
        "text": "",
        "artifacts": artifacts,
        "usage": usage,
        "error": error_msg,
        "steps": steps,
    }
