[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "numa-recent-jobs"
version = "0.1.0"
description = "Lambda function for tracking recent jobs in Numa applications"
authors = ["Arcanum AI"]
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

boto3 = "^1.34.0"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "1.40.21"
mypy = "1.17.1"
pylint = "3.3.8"
pyright = "1.1.403"
