[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "numa-recent-jobs"
version = "0.1.0"
description = "Lambda function for tracking recent jobs in Numa applications"
authors = ["Arcanum AI"]
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

boto3 = "^1.34.0"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "1.37.15"
mypy = "1.15.0"
pylint = "3.3.5"
pyright = "1.1.396"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.9.0"
poetry-plugin-lambda-build = ">=1.0.7"

[tool.poetry-plugin-lambda-build]
package-artifact-path = "lambda_function.zip"
without = "dev"
