export type IconOption = { value: string; label: string };

// Expanded catalog of Bootstrap icon class names for agents
export const AGENT_ICON_CATALOG: IconOption[] = [
  { value: 'bi bi-robot', label: 'Assistant' },
  { value: 'bi bi-lightning-charge', label: 'Automation' },
  { value: 'bi bi-journal-text', label: 'Documentation' },
  { value: 'bi bi-people', label: 'People Ops' },
  { value: 'bi bi-briefcase', label: 'Business' },
  { value: 'bi bi-graph-up', label: 'Analytics' },
  { value: 'bi bi-shield-check', label: 'Compliance' },
  { value: 'bi bi-gear', label: 'Operations' },
  { value: 'bi bi-cash-stack', label: 'Finance' },
  { value: 'bi bi-bank', label: 'Banking' },
  { value: 'bi bi-bag-check', label: 'Procurement' },
  { value: 'bi bi-bug', label: 'QA' },
  { value: 'bi bi-code-slash', label: 'Developer' },
  { value: 'bi bi-cloud', label: 'Cloud' },
  { value: 'bi bi-hdd-network', label: 'Infra' },
  { value: 'bi bi-shield-lock', label: 'Security' },
  { value: 'bi bi-file-earmark-text', label: 'Reports' },
  { value: 'bi bi-search', label: 'Research' },
  { value: 'bi bi-globe', label: 'Web' },
  { value: 'bi bi-megaphone', label: 'Marketing' },
  { value: 'bi bi-basket', label: 'E‑commerce' },
  { value: 'bi bi-clipboard-check', label: 'Review' },
  { value: 'bi bi-chat-dots', label: 'Support' },
  { value: 'bi bi-headset', label: 'Helpdesk' },
  { value: 'bi bi-envelope-paper', label: 'Email' },
  { value: 'bi bi-calendar-event', label: 'Calendar' },
  { value: 'bi bi-diagram-3', label: 'Workflow' },
  { value: 'bi bi-diagram-3-fill', label: 'Orchestration' },
  { value: 'bi bi-clipboard-pulse', label: 'Health' },
  { value: 'bi bi-building', label: 'Company' },
  { value: 'bi bi-clipboard-data', label: 'Data' },
  { value: 'bi bi-box-seam', label: 'Logistics' },
  { value: 'bi bi-truck', label: 'Shipping' },
  { value: 'bi bi-geo-alt', label: 'Location' },
  { value: 'bi bi-journal-arrow-down', label: 'Intake' },
  { value: 'bi bi-pie-chart', label: 'Insights' },
  { value: 'bi bi-file-earmark-binary', label: 'ETL' },
  { value: 'bi bi-diagram-2', label: 'Process' },
  { value: 'bi bi-boxes', label: 'Inventory' },
  { value: 'bi bi-cpu', label: 'Compute' },
  { value: 'bi bi-rocket', label: 'Launch' },
  { value: 'bi bi-joystick', label: 'Experiment' },
  { value: 'bi bi-speedometer', label: 'Performance' },
  { value: 'bi bi-award', label: 'Quality' },
  { value: 'bi bi-mortarboard', label: 'Training' },
  { value: 'bi bi-person-vcard', label: 'HR' },
  { value: 'bi bi-clipboard', label: 'Policy' },
  { value: 'bi bi-check2-square', label: 'Checklist' },
  { value: 'bi bi-clipboard-check-fill', label: 'Audit' },
];
