[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "structured-data-extraction"
version = "0.1.0"
description = ""
authors = ["Nathan Douglas <nathan@arcanum.ai>"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

bedrock = {path = "../../../lib/bedrock", develop = true}
boto3 = "1.40.21"
structlog = "25.2.0"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "1.40.21"
mypy = "1.17.1"
pylint = "3.3.8"
pyright = "1.1.403"
