include:
  - project: arcanumai/ci
    file: templates/common-jobs.yml
  - project: arcanumai/ci
    file: pipelines/noop.yml

lint:
  stage: lint
  needs: []
  image: python:3.11
  script:
    - pip install pre-commit
    - pre-commit run --all-files

deploy_doc_reconstructor_app:
  stage: deploy
  image: node:20-alpine
  script:
    - cd $TYPE/$NAME                   # Navigate to the project directory
    - yarn install                      # Install dependencies
    - yarn build                        # Compile TypeScript to JavaScript using esbuild
    - cp -r node_modules dist/functions/node_modules  # Copy node_modules into the dist/functions directory
    - cd dist/functions                 # Navigate to the dist/functions directory where compiled code and dependencies are
    - zip -r function.zip .             # Zip the compiled code and node_modules
    - aws lambda update-function-code --function-name document-reconstructor --zip-file fileb://function.zip
  only:
    - main

deploy_numa_frontend:
  stage: deploy
  image: node:20-alpine
  script:
    - cd numa-frontend
    - yarn install
    - yarn build
    - cp -r node_modules dist/
    - cd dist
    - zip -r frontend.zip .
    - aws s3 cp frontend.zip s3://my-bucket/path/
  only:
    - main
