.clients:
  matrix:
    - CLIENT_NAME:
        - 2gen
        - 30-seconds
        - accumen
        - align-me
        - arcanum-dave
        - arcanum-demo-nathan
        - arcanum-demo-nick
        - arcanum-demo-sam
        - arcanum-demo-sebastian
        - arcanum-hams
        - arcanum-prod-trial
        - asper
        - autoshoppe
        - av-media
        - bendigo-council
        - beyond-expectations
        - broken-hill-city-council
        - classic-group
        - corangamite
        - cuttriss
        - debtworks
        - delta-insurance
        - design-builders
        - ema
        - geofabrics
        - kapiti-coast
        - lg-pro
        - macedon-ranges
        - modern-sales
        - moira-shire-council
        - momentum
        - mornington-peninsula-council
        - mosaic
        - ngati-kahu
        - nzsba
        - rebura
        - rooflogic
        - shire-of-narrogin
        - story-box
        - sydney-test-dave
        - symphony
        - tda
        - transit
        - w-advisory
        - warrnambool-city-council
