.clients:
  matrix:
    - CLIENT_NAME:
        - 30-seconds
        - accumen
        - align-me
        - arcanum-council-trial
        - arcanum-dave
        - arcanum-demo-nathan-2
        - arcanum-demo-nick
        - arcanum-demo-sam
        - arcanum-demo-sydney
        - dev-hams
        - arcanum-prod-numa-demo
        - arcanum-prod-trial
        - av-media
        - bendigo-council
        - beyond-expectations
        - broken-hill-city-council
        - classic-group
        - corangamite
        - cuttriss
        - debtworks
        - design-builders
        - geofabrics
        - gracepapers
        - huddle-advisory
        - kapiti-coast
        - lg-pro
        - macedon-ranges
        - modern-sales
        - moira-shire-council
        - momentum
        - mosaic
        - ngati-kahu
        - nolia
        - nzsba
        - shire-of-narrogin
        - springload
        - symphony
        - tda
        - thealternativeboard
        - transit
        - ultrait
        - w-advisory
        - warrnambool-city-council
