include:
  - project: arcanumai/ci
    file: pipelines/pre-commit.yml
  - project: arcanumai/ci
    file: pipelines/infra.yml
  - project: arcanumai/ci
    file: pipelines/node.yml
  - project: arcanumai/ci
    file: pipelines/python.yml

variables:
  PYTHON_VER: "3.12"

.node_job:
  variables:
    BUILD_DIR: tools

.python-matrix:
  matrix:
    - PYTHON_WORKING_DIRECTORY:
        - deployer
        - lambdas/extract-content-from-file-general
        - lambdas/extract-content-from-pdf-structured
        - lambdas/meeting-tools-app-formatting

python-lint:
  extends: .poetry-job
  needs: []
  parallel:
    !reference [.python-matrix]
  script:
    - poetry run pylint . --verbose --recursive yes --ignore .venv
    - poetry run mypy .
    - poetry run pyright .

python-test:
  parallel:
    !reference [.python-matrix]
