AWSTemplateFormatVersion: 2010-09-09
Resources:
  ArcanumAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::324037291751:root
            Action:
              - sts:AssumeRole
      Description: Admin role that Arcanum AI can use to setup resources
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: ArcanumAIAccess
