[tool.poetry]
name = "aws-q-apps-deployer"
package-mode = false
version = "0.1.0"
description = ""
authors = ["Nick6464 <49857434+Nick6464@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.35.0"
streamlit = "^1.37.1"
python-dotenv = "^1.0.1"
streamlit-oauth = "^0.1.13"
pyjwt = "^2.9.0"
streamlit-feedback = "^0.1.3"
uuid = "^1.30"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
