[tool.poetry]
name = "bedrock"
version = "0.1.0"
description = ""
authors = ["Arcanum AI"]
readme = "README.md"
packages = [
    { include = "bedrock" },
]

[tool.poetry.dependencies]
python = "^3.12"

boto3 = "1.35.76"
filetype = "1.2.0"
structlog = "24.4.0"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "1.35.76"
mypy = "1.13.0"
pylint = "3.3.2"
pyright = "1.1.389"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
