[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "bedrock"
version = "0.1.0"
description = ""
authors = ["Arcanum AI"]
readme = "README.md"
packages = [
    { include = "bedrock" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

boto3 = ">1,<2"
filetype = "1.2.0"
structlog = "25.2.0"
prm = {path = "../prm", develop = true}

[tool.poetry.group.dev.dependencies]
boto3-stubs = {extras = ["essential"], version = "^1.38.46"}
pylint = "3.3.8"
pyright = "1.1.403"
mypy = "^1.16.1"
