[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "recruitment-job-ad-creation"
version = "0.1.0"
description = ""
authors = ["ArcanumAI"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"
bedrock = {path = "../../../lib/bedrock", develop = true}
boto3 = "1.37.20"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "1.37.20"
mypy = "1.15.0"
pylint = "3.3.6"
pyright = "1.1.398"
