[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "web-search-proxy"
version = "0.1.0"
description = "Web search proxy that returns content using Google search and a simple scraper"
authors = ["Arcanum AI"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"
httpx = "^0.28.1"
structlog = "^25.2.0"
aws-lambda-powertools = "^2.32.0"
boto3 = "^1.29.0"
googlesearch-python = "^1.1.0"
beautifulsoup4 = "^4.12.2"
bedrock = {path = "../../../lib/bedrock", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-mock = "^3.11.1"
pytest-cov = "^4.1.0"
pytest-env = "^1.0.1"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.9.0"
poetry-plugin-lambda-build = ">=1.0.7"

[tool.poetry-plugin-lambda-build]
package-artifact-path = "lambda_function.zip"
without = "dev"

[tool.black]
line-length = 100
target-version = ["py313"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "--cov=. --cov-report=term-missing"
env = [
    "LOG_LEVEL=INFO",
]
