[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.mypy]
python_version = "3.13"
ignore_missing_imports = true

[tool.poetry]
name = "web-search-proxy"
version = "0.1.0"
description = "Web search proxy that returns content using Google search and a simple scraper"
authors = ["Sam Bentley <sam@arcanum.ai>"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

httpx = "^0.28.1"
structlog = "^25.2.0"
aws-lambda-powertools = "3.9.0"
googlesearch-python = "^1.1.0"
beautifulsoup4 = "^4.12.2"
bedrock = {path = "../../../lib/bedrock", develop = true}
helpers = {path = "../../../lib/helpers", develop = true}

[tool.poetry.group.dev.dependencies]
mypy = "1.17.1"
pylint = "3.3.8"
pyright = "1.1.403"
