[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "aggregate-candidate-results"
version = "0.1.0"
description = "Lambda to aggregate JSON results from candidate-screening lambda"
authors = ["Sam Bentley <sam@arcanum.ai>"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"
helpers = {path = "../../../lib/helpers", develop = true}
s3_helpers = {path = "../../../lib/s3_helpers", develop = true}
aws-lambda-powertools = "3.9.0"
structlog = "25.2.0"

[tool.poetry.group.dev.dependencies]
mypy = "1.15.0"
pylint = "3.3.6"
pyright = "1.1.398"
pre-commit = "^4.1.0"
pytest = "^8.3.4"
