[tool.poetry]
name = "example-1"
version = "0.1.0"
description = ""
authors = ["ArcanumAI"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"
boto3 = "^1.36.5"

[tool.poetry.group.dev.dependencies]
mypy = "1.13.0"
pylint = "3.3.2"
pyright = "1.1.391"
pre-commit = "^4.1.0"
poetry-plugin-lambda-build = "^1.0.7"
pytest = "^8.3.4"
boto3-stubs = "^1.36.3"

[tool.poetry-plugin-lambda-build]
package-artifact-path = "lambda_function.zip"
without = "dev"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
