import { useCallback } from 'react';
import { useLocation } from 'react-router-dom';
import { useAuth } from '../../Providers/AuthProvider';
import { useNumaRequest } from '../../Providers/NumaRequestContext';
import { AdminAgentsService } from '../../Services/AdminAgentsService';
import { getFlag } from '../../utils/featureFlags';
import type { AskNumaContextFile } from '../AskNuma/AskNumaPopup';

export const SUPPORT_ENVIRONMENT_FILENAME = 'numa-environment.md';

/**
 * Collect every feature flag from sessionStorage. Config loading writes each
 * boolean config value as `DEPLOY_<NAME>` (raw deploy value) plus `<NAME>`
 * (live value, admin-toggleable) — see ConfigSetup.tsx. The effective value
 * comes from getFlag(), which combines both.
 */
function collectFeatureFlags(): Array<{ name: string; enabled: boolean }> {
  const flags: Array<{ name: string; enabled: boolean }> = [];
  for (let i = 0; i < sessionStorage.length; i++) {
    const key = sessionStorage.key(i);
    if (key?.startsWith('DEPLOY_')) {
      const name = key.slice('DEPLOY_'.length);
      flags.push({ name, enabled: getFlag(name) });
    }
  }
  return flags.sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Builds the `numa-environment.md` report attached to Support popup
 * conversations (FEAT-204). Gives the support agent context on the user's
 * environment: client, version, current page, feature flags, and global
 * admin settings — so it can tell "feature not enabled" apart from "bug"
 * without asking the user.
 */
export function useSupportEnvironmentContext(): () => Promise<AskNumaContextFile[]> {
  const location = useLocation();
  const { user } = useAuth();
  const { numaGet } = useNumaRequest();

  return useCallback(async (): Promise<AskNumaContextFile[]> => {
    const idToken = user?.decoded_tokens?.idToken;
    const groups = (idToken?.['cognito:groups'] as string[] | undefined) || [];

    // Global admin settings — best effort; some calls may not be available
    // to every user. Missing data is reported as "unknown", never an error.
    let agentsMode = 'unknown';
    try {
      agentsMode = (await AdminAgentsService.get(numaGet)).mode;
    } catch {
      // Leave as unknown
    }

    const flags = collectFeatureFlags();
    const lines = [
      '# Numa Environment Report',
      '',
      'Auto-generated by the Support popup when this conversation started.',
      '',
      '## Instance',
      `- Client: ${sessionStorage.getItem('CLIENT_NAME') || 'unknown'}`,
      `- Numa version: ${sessionStorage.getItem('NUMA_VERSION') || 'unknown'}`,
      `- Region: ${sessionStorage.getItem('REGION') || 'unknown'}`,
      '',
      '## User',
      `- Email: ${idToken?.email || 'unknown'}`,
      `- Groups: ${groups.length > 0 ? groups.join(', ') : 'none'}`,
      '',
      '## Current Page',
      `- Path: ${location.pathname}${location.search}`,
      '',
      '## Global Admin Settings',
      `- Agents mode: ${agentsMode}`,
      '',
      '## Feature Flags (effective values)',
      ...flags.map((f) => `- ${f.name}: ${f.enabled ? 'enabled' : 'disabled'}`),
      '',
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
    return [{ filename: SUPPORT_ENVIRONMENT_FILENAME, blob }];
  }, [location.pathname, location.search, user, numaGet]);
}
