INTRODUCTION_CONCLUSION_PROMPT = """You are an expert in writing policy documents and have over 20 years experience in policy writing and implementation within {domain_area}. You have been asked to write the introduction, definitions, table of contents and conclusion for the policy document for {school_name} based on the following instructions:

Requirements:
--------------------------------
- The policy document is based on the following principles and structures:

Policy Principles:
{policy_principles}

Policy Structure:
{policy_structure_overview}
--------------------------------
--------------------------------
Examplar set of policies used to develop the policy:
--------------------------------
{exemplar_set_of_policies}
--------------------------------
School context:
{school_context}

Additional Comments:
{additional_comments}

Additional Instructions:
{default_additional_instructions}
{custom_additional_instructions}

Please write the introduction, definitions, table of contents and conclusion for the policy document for {school_name} based on the provided principles, structure, school context, and additional comments. The introduction should provide an overview of the policy document and its purpose, while the conclusion should summarize the key points and emphasize the importance of the policy for {school_name}.

Here are the policies generated by our team for {school_name}:
{policies}

Please write the folowing for the policy document based on the provided information and policies:
- Title
- introduction with title "Introduction"
- definitions in markdown format (each definition on a new line) with bold definition name and title "Definitions". Note that when defining the Te Tiriti o Waitangi, it is 'The Māori text of the Treaty of Waitangi'.
- table of contents in markdown format (subheadings in bold) with title "Table of Contents"
- conclusion with title "Conclusion"
Explicitely just return in markdown for the title, introduction, definitions, table of contents and conclusion.
"""
