/**
 * Tool-invoke dispatcher — the CLI's generic action surface. Each `numa
 * <category> <action>` invocation lands here as a `{tool, params, context,
 * id_token}` request; we route to the right downstream Lambda based on the
 * tool's entry in `registry.ts`.
 *
 * Two downstream shapes today (see `registry.ts`):
 *   - workspace_chat_tools (event-shaped) — the default for unregistered
 *     tools. Forwards verbatim and translates the response.
 *   - kb_manager (REST-shaped) — for file-management ops the chat-tools
 *     dispatcher doesn't have. Built as a synthetic API Gateway event,
 *     including the CloudFront shared secret kb_manager gates on.
 *
 * Trust model:
 *   - `user_sub` comes from the JWT (server-trusted).
 *   - `allowed_kbs` / `allowed_kbs_with_names` are scoping hints the CLI
 *     forwards. They CAN'T grant access — downstream Lambdas enforce
 *     per-KB ownership/membership in DynamoDB.
 *   - `id_token` is the raw Cognito ID token, needed by some
 *     workspace-chat-tools handlers for AssumeRoleWithWebIdentity.
 */

import type { AuthContext } from '../shared/auth.js';
import { CLIENT_NAME, CLOUDFRONT_SHARED_SECRET, NUMA_OPS_ENABLED } from '../shared/config.js';
import { errorResponse, jsonResponse, type HttpResponse } from '../shared/response.js';
import { createApprovalRequest, pollApproval } from './approval.js';
import { invokeChatTools } from './dispatch-chat-tools.js';
import { invokeKbManager, MissingPathParamError } from './dispatch-kb-manager.js';
import { invokeOauthTools } from './dispatch-oauth-tools.js';
import { isToolAllowedForAgentType } from './policy.js';
import { resolveToolRoute } from './registry.js';

export interface ToolInvokeRequest {
  tool: string;
  params?: Record<string, unknown>;
  context?: {
    allowed_kbs?: Array<{ id: string; name?: string }>;
    allowed_kb_operations?: string[];
    conversation_id?: string;
    /** Frontend-set tool toggles. Forwarded as `allowed_tools` to
     * workspace-chat-tools, which gates certain categories on it
     * (memories_tool, create_agent_tool, integration slugs). */
    enabled_tools?: string[];
    /** Agent type id (Phase 5). Drives the per-type CLI category allow-list
     * (see policy.ts). Trusted-env channel — empty on the laptop path. */
    agent_type?: string;
  };
  id_token?: string;
  /**
   * Required user-facing caption — CLI supplies this on every tool call so
   * the chat UI can render `(tool icon) Numa <category>: <user_message>`.
   * Forwarded to workspace-chat-tools as both `event.user_message` (new
   * canonical location) AND `params.description` (back-compat with
   * existing approval handlers).
   */
  user_message?: string;
  /**
   * Approval request ID (UUID). When present with auto_approved=false,
   * the Lambda creates a DDB approval record and polls until the user
   * approves/denies/times out. Only dispatches downstream on approval.
   * Generated by the CLI for write ops in workspace-IAM mode.
   */
  request_id?: string;
}

export const handleToolInvoke = async (auth: AuthContext, body: ToolInvokeRequest): Promise<HttpResponse> => {
  if (!body.tool || typeof body.tool !== 'string') {
    return errorResponse(400, "Missing or invalid 'tool' field");
  }

  // ── Numa Ops entitlement gate ─────────────────────────────────────────
  // Hard server-side gate restoring what the MCP-registration check used to
  // enforce: ops_* operations only run for clients with Ops enabled. The
  // broad `Bash(numa:*)` CLI permission lets the LLM call `numa ops <op>`
  // regardless of entitlement, so we stop it here — before any approval
  // record is created or any downstream Lambda is invoked. Only `ops_*` is
  // gated; every other tool category is unaffected.
  if (body.tool.startsWith('ops_') && !NUMA_OPS_ENABLED) {
    return jsonResponse(200, {
      status: 'error',
      message: 'Numa Ops is not enabled for this workspace.',
    });
  }

  // ── Per-agent-type CLI allow-list (Phase 5) ───────────────────────────
  // Restricted agent types (e.g. Nolia, which processes untrusted documents)
  // may only use a subset of CLI categories. Enforce here — before any
  // approval record or downstream dispatch — keyed on the agent type the CLI
  // forwards in context. Unrestricted types (no agent_type, or one with no
  // policy) pass straight through. See policy.ts for the trust model.
  const verdict = isToolAllowedForAgentType(body.context?.agent_type, body.tool);
  if (!verdict.allowed) {
    const allowed = verdict.allowedCategories?.join(', ') ?? '';
    return jsonResponse(200, {
      status: 'error',
      message:
        `This agent is not permitted to use that Numa command` +
        (verdict.category ? ` (category: ${verdict.category})` : '') +
        (allowed ? `. Permitted categories: ${allowed}.` : '.'),
    });
  }

  const autoApproved = !!body.params?.auto_approved;
  const requestId = body.request_id ?? (body.params?.request_id as string | undefined);

  // ── Centralised approval gate ─────────────────────────────────────────
  // When the CLI sends auto_approved=false + a request_id, it has already
  // emitted the SSE approval card to the frontend. We create the DDB
  // record here and poll until the user clicks Approve/Deny (or timeout).
  // Only dispatch downstream on approval — denied/timeout short-circuit.
  if (!autoApproved && requestId) {
    try {
      await createApprovalRequest({
        userSub: auth.sub,
        actionKey: deriveActionKey(body),
        description: body.user_message ?? '',
        propsPreview: derivePropsPreview(body),
        approvalId: requestId,
      });
      const { decision, denyReason } = await pollApproval(requestId);
      if (decision === 'denied') {
        return jsonResponse(200, {
          status: 'denied',
          message: denyReason
            ? `The user denied this action. The user said: "${denyReason}"`
            : 'The user denied this action.',
          deny_reason: denyReason,
          approval_id: requestId,
        });
      }
      if (decision === 'unattended') {
        return jsonResponse(200, {
          status: 'unattended',
          message:
            'The user was not viewing the conversation, so the approval prompt was ' +
            'never shown to them. The action was NOT executed. Do not retry ' +
            'automatically — summarise what you wanted to do and let the user know ' +
            'they can ask again when they are back.',
          approval_id: requestId,
        });
      }
      if (decision === 'timeout') {
        return jsonResponse(200, {
          status: 'timeout',
          message: 'Approval timed out',
          approval_id: requestId,
        });
      }
      // approved → dispatch with auto_approved=true so the Python handler
      // skips its own DDB approval block.
      body.params = { ...(body.params ?? {}), auto_approved: true, request_id: requestId };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return errorResponse(500, `approval orchestration failed: ${msg}`);
    }
  }

  // ── Dispatch ──────────────────────────────────────────────────────────
  const route = resolveToolRoute(body.tool);
  const params = body.params ?? {};
  const allowedKbs = body.context?.allowed_kbs ?? [];
  const conversationId = body.context?.conversation_id ?? '';
  const enabledTools = body.context?.enabled_tools ?? [];
  const idToken = body.id_token ?? '';

  try {
    if (route.target === 'workspace_chat_tools') {
      const result = await invokeChatTools({
        clientName: CLIENT_NAME,
        tool: body.tool,
        params,
        userSub: auth.sub,
        userEmail: auth.email ?? '',
        userGroups: auth.groups,
        allowedKbs,
        enabledTools,
        conversationId,
        idToken,
        userMessage: body.user_message,
        requestId,
      });
      if (result.status === 'error') return jsonResponse(400, result);
      return jsonResponse(200, result);
    }

    if (route.target === 'oauth_workspace_tools') {
      const result = await invokeOauthTools({
        clientName: CLIENT_NAME,
        tool: body.tool,
        params,
        userSub: auth.sub,
        conversationId,
      });
      if (result.status === 'error') return jsonResponse(400, result);
      return jsonResponse(200, result);
    }

    // kb_manager target — synthetic REST call.
    const result = await invokeKbManager({
      clientName: CLIENT_NAME,
      cloudfrontSecret: CLOUDFRONT_SHARED_SECRET,
      accessToken: auth.accessToken,
      method: route.method,
      pathTemplate: route.pathTemplate,
      params,
    });
    if (result.statusCode < 200 || result.statusCode >= 300) {
      return jsonResponse(result.statusCode, { status: 'error', result: null, error: result.body });
    }
    return jsonResponse(200, { status: 'success', result: result.body });
  } catch (err) {
    if (err instanceof MissingPathParamError) {
      return errorResponse(400, err.message);
    }
    const message = err instanceof Error ? err.message : String(err);
    return errorResponse(500, `tool invoke failed: ${message}`);
  }
};

/**
 * Derive the DDB action_key from the tool invoke request. Must match what
 * the Python handlers produce today so approval cards + DDB rows align.
 */
function deriveActionKey(body: ToolInvokeRequest): string {
  const tool = body.tool;
  const params = body.params ?? {};

  // ops_* → "ops-<op-with-dashes>"
  if (tool.startsWith('ops_')) {
    const op = String(params.operation ?? tool.slice(4));
    return `ops-${op.replace(/_/g, '-')}`;
  }
  // pipedream_run_action → "integration-<slug>"
  if (tool === 'pipedream_run_action') {
    const actionKey = String(params.action_key ?? '');
    const slug = actionKey.split('-')[0] || 'unknown';
    return `integration-${slug}`;
  }
  // pipedream_proxy_request → "proxy_<METHOD>"
  if (tool === 'pipedream_proxy_request') {
    const method = String(params.method ?? 'POST').toUpperCase();
    return `proxy_${method}`;
  }
  // connect_request → "connect-<METHOD>"
  if (tool === 'connect_request') {
    const method = String(params.method ?? 'POST').toUpperCase();
    return `connect-${method}`;
  }
  // agents
  if (tool === 'create_agent') return 'numa_agents_create';
  if (tool === 'update_agent') return 'numa_agents_update';
  if (tool === 'patch_agent_prompt') return 'numa_agents_patch_prompt';
  if (tool === 'duplicate_agent') return 'numa_agents_duplicate';
  if (tool === 'delete_agent') return 'numa_agents_delete';
  // memories
  if (tool === 'user_profile_add_memory') return 'numa_memories_add';
  if (tool === 'user_profile_update_memory') return 'numa_memories_update';
  if (tool === 'user_profile_delete_memory') return 'numa_memories_delete';
  // files (KB)
  if (tool === 'add_to_kb') return 'numa_knowledgeBases_upload';
  if (tool === 'delete_kb_file') return 'numa_knowledgeBases_delete';

  return `cli-${tool.replace(/_/g, '-')}`;
}

function derivePropsPreview(body: ToolInvokeRequest): Record<string, unknown> {
  const params = body.params ?? {};
  const tool = body.tool;

  if (tool.startsWith('ops_')) {
    return (params.params as Record<string, unknown>) ?? {};
  }
  if (tool === 'pipedream_run_action') {
    const props = params.configured_props ?? params.props ?? {};
    const serialized = JSON.stringify(props);
    if (serialized.length > 2048) {
      return { _truncated: true, _length: serialized.length };
    }
    return props as Record<string, unknown>;
  }
  if (tool === 'pipedream_proxy_request' || tool === 'connect_request') {
    return { method: params.method, url: params.upstream_url ?? params.url };
  }
  if (tool.includes('agent')) {
    const { title, visibility, agent_id } = params;
    return { title, visibility, agent_id } as Record<string, unknown>;
  }
  if (tool.includes('memory')) {
    const { id, memory } = params;
    const preview = typeof memory === 'string' && memory.length > 200 ? memory.slice(0, 200) + '…' : memory;
    return { id, memory: preview } as Record<string, unknown>;
  }
  if (tool === 'add_to_kb' || tool === 'delete_kb_file') {
    return { kb_id: params.kb_id, filename: params.filename };
  }
  return {};
}
