"""OAuth workspace tools package."""

from .connect_tools import (
    handle_connect_netsuite_mcp,
    handle_connect_request,
    handle_connect_status,
    handle_connect_synergy_companies,
    handle_connect_synergy_contacts,
    handle_connect_synergy_download,
    handle_connect_synergy_exact_term,
    handle_connect_synergy_file_history,
    handle_connect_synergy_file_info,
    handle_connect_synergy_folder_summary,
    handle_connect_synergy_forums,
    handle_connect_synergy_issues,
    handle_connect_synergy_job_extras,
    handle_connect_synergy_job_meta,
    handle_connect_synergy_job_stats,
    handle_connect_synergy_job_tree,
    handle_connect_synergy_list,
    handle_connect_synergy_notes,
    handle_connect_synergy_portfolio,
    handle_connect_synergy_projects,
    handle_connect_synergy_recent,
    handle_connect_synergy_resolve,
    handle_connect_synergy_schema,
    handle_connect_synergy_search,
    handle_connect_synergy_status,
    handle_connect_synergy_tasks,
    handle_connect_synergy_transmittals,
    handle_connect_synergy_users,
    handle_connect_synergy_webforms,
    handle_connect_synergy_workflow,
)
from .oauth_tools import (
    handle_oauth_connection_status,
    handle_oauth_download_file,
    handle_oauth_get_file_metadata,
    handle_oauth_list_files,
    handle_oauth_search_files,
)

__all__ = [
    # OAuth handlers (existing)
    "handle_oauth_list_files",
    "handle_oauth_download_file",
    "handle_oauth_search_files",
    "handle_oauth_get_file_metadata",
    "handle_oauth_connection_status",
    # Connect handlers (unified)
    "handle_connect_status",
    "handle_connect_synergy_list",
    "handle_connect_synergy_search",
    "handle_connect_synergy_download",
    "handle_connect_synergy_job_meta",
    "handle_connect_synergy_folder_summary",
    "handle_connect_synergy_schema",
    "handle_connect_synergy_file_info",
    "handle_connect_synergy_job_stats",
    "handle_connect_synergy_job_tree",
    "handle_connect_synergy_portfolio",
    "handle_connect_synergy_exact_term",
    # Connect handlers — Synergy read-tools Wave 1
    "handle_connect_synergy_tasks",
    "handle_connect_synergy_contacts",
    "handle_connect_synergy_issues",
    "handle_connect_synergy_workflow",
    "handle_connect_synergy_file_history",
    "handle_connect_synergy_recent",
    # Connect handlers — Synergy read-tools Wave 2
    "handle_connect_synergy_forums",
    "handle_connect_synergy_projects",
    "handle_connect_synergy_transmittals",
    "handle_connect_synergy_companies",
    "handle_connect_synergy_webforms",
    "handle_connect_synergy_job_extras",
    "handle_connect_synergy_notes",
    "handle_connect_synergy_status",
    "handle_connect_synergy_users",
    # Connect handlers — Synergy read-tools Wave 3
    "handle_connect_synergy_resolve",
    "handle_connect_request",
    "handle_connect_netsuite_mcp",
]
