[tool.poetry]
name = "numa-recent-jobs"
version = "0.1.0"
description = "Lambda function for tracking recent jobs in Numa applications"
authors = ["Arcanum AI"]
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.34.0"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "1.35.76"
mypy = "1.13.0"
pylint = "3.3.2"
pyright = "1.1.389"

[tool.poetry-plugin-lambda-build]
package-artifact-path = "lambda_function.zip"
without = "dev"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
