[tool.poetry]
name = "step-function-status"
version = "0.1.0"
description = ""
authors = ["ArcanumAI"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.12.0"

boto3 = "1.35.72"
helpers = {path = "../../lib/helpers", develop = true}
structlog = "24.4.0"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "1.35.72"
mypy = "1.13.0"
pylint = "3.3.2"
pyright = "1.1.389"

[tool.poetry-plugin-lambda-build]
package-artifact-path = "lambda_function.zip"
without = "dev"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
