[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "financial-analysis-data-extraction"
version = "0.1.0"
description = ""
authors = ["ArcanumAI"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"
bedrock = {path = "../../../lib/bedrock", develop = true}
boto3 = "1.36.13"
structlog = "25.2.0"

[tool.poetry.group.dev.dependencies]
mypy = "1.15.0"
pylint = "3.3.5"
pyright = "1.1.396"
boto3-stubs = "^1.35.96"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.9.0"
poetry-plugin-lambda-build = ">=1.0.7"

[tool.poetry-plugin-lambda-build]
package-artifact-path = "lambda_function.zip"
without = "dev"
