[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "meeting-analyser"
version = "0.1.0"
description = ""
authors = ["ArcanumAI"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

aws-lambda-powertools = "3.9.0"
bedrock = {path = "../../../lib/bedrock", develop = true}
helpers = {path = "../../../lib/helpers", develop = true}
s3_helpers = {path = "../../../lib/s3_helpers", develop = true}

[tool.poetry.group.dev.dependencies]
mypy = "1.17.1"
pylint = "3.3.8"
pyright = "1.1.403"
