[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "aws-transcribe"
version = "0.1.0"
description = "AWS Transcribe service wrapper"
authors = ["Sam Bentley <sam@arcanum.ai>"]
packages = [
    { include = "aws_transcribe" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

boto3 = "1.37.20"
structlog = "25.2.0"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "1.37.20"
mypy = "1.15.0"
pylint = "3.3.6"
pyright = "1.1.400"
