/**
 * Shared configuration for supported Pipedream integrations across infrastructure
 *
 * ⚠️ The slug list is mirrored in Python at
 * `lambdas/python/workspace-chat-tools/tools/user_profile.py`
 * (`_PIPEDREAM_INTEGRATION_SLUGS`) for memory-scope validation — that Lambda
 * can't import TS. Add/rename a slug here → mirror it there in the same commit.
 */
export const SUPPORTED_INTEGRATIONS = [
  'gmail',
  'microsoft_outlook',
  'microsoft_outlook_calendar',
  'slack',
  'google_calendar',
  'xero_accounting_api',
  'hubspot',
  'notion',
  'apollo_io',
  'pipedrive',
  'jira',
  'linkedin',
  'google_drive',
  'google_analytics',
  'sharepoint',
  'salesforce_rest_api',
  'asana',
  'onenote',
  'trello',
  'whatsapp_business',
  'mailchimp',
  'freshdesk',
  'rentman',
  'podio',
  'google_sheets',
  'google_forms',
  'google_docs',
  'telegram_bot_api',
  'microsoft_teams',
  'zoom',
  'microsoft_excel',
  'smartsheet',
  'box',
  'zoho_books',
  'odoo',
  'jobber',
  'canva',
  'google_tag_manager',
  'webflow',
  'dropbox',
  'survey_monkey',
  'monday',
  'procore',
  'quickbooks',
  'harvest',
  'alchemer',
  'microsoft_sql_server',
  'microsoft_dynamics_365_sales',
  'dynamics_365_business_central_api',
  'clickup',
  'google_ads',
  'zoho_crm',
  'microsofttodo',
  'fathom',
  'elevenlabs',
  'heygen',
  'gitlab',
  'github',
  'airtable_oauth',
  'google_slides',
  'todoist',
  'google_my_business',
  'streak',
] as const;

export type SupportedIntegration = (typeof SUPPORTED_INTEGRATIONS)[number];
