[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "restart-crawler"
version = "0.1.0"
description = "Lambda function for restarting web crawler execution when approaching history limit"
authors = ["Sam Bentley <sam@arcanum.ai>"]
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"
prm = {path = "../../../lib/prm", develop = true}
aws-lambda-powertools = "^2.24.0"
structlog = "^23.1.0"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "^1.37.20"
mypy = "^1.15.0"
pylint = "^3.3.6"
pyright = "^1.1.400"
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
[tool.poetry.group.boto.dependencies]
boto3 = "1.40.25"
