import { marked } from 'marked';
import HTMLtoDOCX from 'html-to-docx-lite';

const MdToDocx = () => {
  // Function to convert Markdown to DOCX
  const convertMarkdownToDocx = async (markdownString, fileName = 'output.docx') => {
    try {
      // Convert Markdown to HTML with proper styling
      const htmlString = marked.parse(markdownString, {
        headerIds: false,
        mangle: false
      });

      const documentOptions = {
        font: 'Calibri',
        fontSize: 22,
        margins: {
          top: 1440,
          right: 1440,
          bottom: 1440,
          left: 1440,
          header: 720,
          footer: 720,
        },
        title: fileName.replace('.docx', ''),
        creator: 'Numa Policy Builder',
        description: 'Generated by Numa Policy Builder',
        pageSize: {
          width: 12240,
          height: 15840,
        },
        footer: true,
        pageNumber: true,
        table: {
          row: {
            cantSplit: true
          }
        },
        lineNumber: false,
        lang: 'en-NZ',
        complexScriptFontSize: 22,
        skipFirstHeaderFooter: false
      };

      // Convert HTML to DOCX with styling options
      const docxBuffer = await HTMLtoDOCX(
        htmlString,
        null,  // header HTML string
        documentOptions,
        '<p></p>'  // footer HTML string (required when footer is true)
      );

      // Create a Blob from the DOCX buffer
      const blob = new Blob([docxBuffer], {
        type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      });

      // Create a link element to download the file
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = fileName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      console.error('Error converting Markdown to DOCX:', error);
    }
  };

  return { convertMarkdownToDocx };
};

export default MdToDocx;
