[tool.poetry]
name = "aws-q-apps-deployer"
package-mode = false
version = "0.1.0"
description = ""
authors = ["Nick6464 <49857434+Nick6464@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12.0"

boto3 = "1.35.55"
pyjwt = "2.9.0"
python-dotenv = "1.0.1"
streamlit = "1.40.0"
streamlit-feedback = "0.1.3"
streamlit-oauth = "0.1.14"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "1.35.56"
mypy = "1.10.1"
pylint = "3.2.5"
pyright = "1.1.371"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
