[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "costing-calculator"
version = "0.1.0"
description = "A Lambda function for automated DecraShape and FourPlus costing calculations"
authors = ["Sam Bentley <sam@arcanum.ai>"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

aws-lambda-powertools = "3.9.0"
bedrock = {path = "../../../lib/bedrock", develop = true}
helpers = {path = "../../../lib/helpers", develop = true}
s3_helpers = {path = "../../../lib/s3_helpers", develop = true}

[tool.poetry.group.dev.dependencies]
mypy = "1.15.0"
pylint = "3.3.7"
pyright = "1.1.401"
