[tool.poetry]
name = "markdown-to-pdf"
version = "0.1.0"
description = ""
authors = ["Arcanum AI"]
readme = "README.md"
packages = [
    { include = "markdown_to_pdf" },
]

[tool.poetry.dependencies]
python = "^3.12"

fpdf2 = "2.8.1"

[tool.poetry.group.dev.dependencies]
mypy = "1.13.0"
pylint = "3.3.2"
pyright = "1.1.390"
types-fpdf2 = "2.8.1.20241204"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
