[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "markdown-to-pdf"
version = "0.1.0"
description = ""
authors = ["Arcanum AI"]
readme = "README.md"
packages = [
    { include = "markdown_to_pdf" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

markdown-it-py = "3.0.0"
xhtml2pdf = "0.2.17"

[tool.poetry.group.dev.dependencies]
mypy = "1.15.0"
pylint = "3.3.7"
pyright = "1.1.401"
