[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "**/tests/**/*"
]
source = [
    ".",
]

[tool.poetry]
name = "extract-content-from-file-general"
version = "0.1.0"
description = ""
authors = ["Nathan Douglas <nathan@arcanum.ai>"]
readme = "README.md"
packages = [
    { include = "**/*.py" },
]

[tool.poetry.dependencies]
python = "~3.13.0"

aws-transcribe = {path = "../../../lib/aws-transcribe", develop = true}
bedrock = {path = "../../../lib/bedrock", develop = true}
helpers = {path = "../../../lib/helpers", develop = true}
structlog = "25.2.0"
openpyxl = "^3.1.5"
python-docx = "^1.1.2"
PyMuPDF = "^1.24.0,<1.26.1"
Pillow = "^10.0.0"
opentelemetry-instrumentation-threading = "0.54b1"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "1.40.25"
mypy = "1.17.1"
pylint = "3.3.8"
pyright = "1.1.403"
openpyxl-stubs = "^0.1.25"
[tool.poetry.group.boto.dependencies]
boto3 = "1.40.25"
