/**
 * AssistantAdviceBlock - Collapsible pre-analysis display for workspace mode.
 *
 * Shows the pre-request assistant's recommendations in a collapsible block.
 * This advice is generated by a fast model (Nova 2 Lite) before the main
 * Numa agent runs, providing hints and recommendations.
 *
 * Similar to ThinkingBlock but with different styling to distinguish it.
 */
import { useState } from 'react';
import { Collapse, Button } from 'react-bootstrap';
import { useTranslation } from 'react-i18next';
import type { WorkspaceChatAssistantAdviceSegment } from '../../types/workspaceChatTypes';

interface AssistantAdviceBlockProps {
  segment: WorkspaceChatAssistantAdviceSegment;
}

export function AssistantAdviceBlock({ segment }: AssistantAdviceBlockProps) {
  const { t } = useTranslation('chat');
  // Default to collapsed (closed) if not specified
  const [isOpen, setIsOpen] = useState(segment.collapsed === false);

  // Don't render empty advice blocks
  if (!segment.text || !segment.text.trim()) {
    return null;
  }

  return (
    <div className="assistant-advice-block mb-2">
      <Button
        variant="link"
        size="sm"
        onClick={() => setIsOpen(!isOpen)}
        className="assistant-advice-toggle p-0 text-muted d-flex align-items-center"
        aria-controls="assistant-advice-collapse"
        aria-expanded={isOpen}
      >
        <i className={`bi ${isOpen ? 'bi-chevron-down' : 'bi-chevron-right'} me-1`} />
        <i className="bi bi-robot me-1" />
        <span className="small">{t('workspace.assistantAdvice.label')}</span>
      </Button>
      <Collapse in={isOpen}>
        <div id="assistant-advice-collapse">
          <div className="assistant-advice-content mt-1 p-2 bg-light rounded border-start border-3 border-info">
            <pre className="mb-0 small text-muted" style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
              {segment.text}
            </pre>
          </div>
        </div>
      </Collapse>
    </div>
  );
}

export default AssistantAdviceBlock;
